app/urls.py
from django.urls import path
from . import views
urlpatterns = [
  path('', views.homeView, name="home"),
  path('pricing/', views.pricingView, name="pricing"),
  path('payment/', views.paymentView, name="payment"),
  path('payment/success/<str:intent_id>/<str:month_year>/<str:plan_name>/<int:price>/<str:s>/<str:e>/', views.successView, name="success"),
  path('payment/cancel/<str:intent_id>/<str:month_year>/<str:plan_name>/<int:price>/<str:s>/<str:e>/', views.cancelView, name="cancel"),
  ]

members/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('login/', views.loginUser, name="login"),
  path('logout/', views.logoutUser, name="logout"),
  path('register/', views.registerUser, name="register"),
  
  ]

richpanel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('app.urls')),
    path('members/', include('members.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from members.models import Profile


class PricingPlan(models.Model):
    PRICING_PLANS = [
        ('mobile', 'Mobile Plan'),
        ('basic', 'Basic Plan'),
        ('standard', 'Standard plan'),
        ('premium', 'Premium Plan'),
    ]

    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    owner = models.OneToOneField(Profile, on_delete=models.CASCADE, null=True, blank=True)
    plan_name = models.CharField(max_length=20, choices=PRICING_PLANS, default='mobile', null=True, blank=True)
    month_year = models.BooleanField(default= True)
    def __str__(self):
        return str(self.owner)

members/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
  id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  username = models.CharField(max_length=200, blank=True, null=True)
  email = models.EmailField(max_length=500, blank=True)
  created = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return str(self.username)

app/forms.py
from django import forms
from django.forms import ModelForm
from .models import PricingPlan

class PricingPlanForm(ModelForm):
    plan_name = forms.ChoiceField(
        choices=PricingPlan.PRICING_PLANS,
        widget=forms.RadioSelect()
    )
    class Meta:
        model = PricingPlan
        fields = ['month_year', 'plan_name']
        labels = {'month_year':'Month/Year','plan_name': 'select pricing plan'}

members/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'username'
        self.fields['email'].widget.attrs['placeholder'] = 'email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm password'

class CustomUserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')

    def __init__(self, *args, **kwargs):
        super(CustomUserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'username'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'

app/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from .models import PricingPlan
from .forms import PricingPlanForm
from django.urls import reverse
import stripe
from django.conf import settings
stripe.api_key = settings.STRIPE_PRIVATE_KEY
import time
from datetime import datetime, timedelta

def homeView(request):
  context= {}
  return render(request, 'index.html', context)


def pricingView(request):
    profile = request.user.profile
    pricing_plan, created = PricingPlan.objects.get_or_create(owner=profile)
    if request.method == 'POST':
      form = PricingPlanForm(request.POST, instance=pricing_plan)
      if form.is_valid():
        form.save()
        return redirect('payment')
    else:
       form = PricingPlanForm(instance=pricing_plan)   
    
    context = {'profile': profile, 'form': form}
    return render(request, 'pricing.html', context)

def paymentView(request):
  profile = request.user.profile
  pricing_plan = PricingPlan.objects.get(owner=profile)
  month_year = pricing_plan.month_year
  plan_name = pricing_plan.plan_name
  context = {}
  PRICE = {
        'mobile': 100,
        'basic': 200,
        'standard': 500,
        'premium': 700,
    }
  price = PRICE.get(plan_name, 0) if  month_year else PRICE.get(plan_name, 0) * 10
  intent = stripe.PaymentIntent.create(
    amount=price,
    currency="inr",
    payment_method_types=["card"],
    metadata={"integration_check": "accept_a_payment"},
  ) 
  current_date = datetime.now()
  if(month_year == True): 
    num = 30
  else: 
    num = 365
  future_date = current_date + timedelta(days=num)
  s = current_date.strftime('%d-%m-%Y')
  e = future_date.strftime('%d-%m-%Y')
  context = {'month_year': month_year, 'plan_name': plan_name, 'price':price, 'client_secret':intent.client_secret, 'profile': profile.username, 's':s, 'e': e}
  
  if request.method == 'POST':
    intent_id = intent.get('id')
    time.sleep(5)
    return redirect('success', intent_id=intent_id, month_year=month_year, plan_name=plan_name, price=price, s=s, e=e)
  
  return render(request, 'payment.html', context)

def successView(request, intent_id, month_year, plan_name, price, s, e):
  if request.method == 'POST':
    return redirect('cancel', intent_id=intent_id, month_year=month_year, plan_name=plan_name, price=price, s=s, e=e)
  context = {'intent_id': intent_id,'month_year': month_year, 'plan_name': plan_name, 'price':price,'s':s, 'e': e}
  return render(request, 'success.html', context)

def cancelView(request, intent_id, month_year, plan_name, price, s,e):
  intent = stripe.PaymentIntent.retrieve(intent_id)
  intent.cancel()
  context = {'intent_id': intent_id,'month_year': month_year, 'plan_name': plan_name, 'price':price,'s':s, 'e': e}
  return render(request, 'cancel.html', context)

members/views.py
from django.http import HttpResponse
from .forms import CustomUserCreationForm, CustomUserLoginForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def loginUser(request):
  page = 'login'
  form = CustomUserLoginForm()
  if request.method == 'POST':
    form = CustomUserLoginForm(data=request.POST)
    username = request.POST.get('username')
    password = request.POST.get('password')
    
    try:
      user = User.objects.get(username=username)
    except:
      messages.error(request, 'User does not exist')
    user = authenticate(request, username=username, password=password)
    if user is not None:
      messages.success(request, 'User logged in successfully')
      login(request, user)
      return redirect('home')
    else:
      messages.error(request, 'username or password is incorrect')
  context = {'page': page, 'form': form}
  return render(request, 'signupin.html', context)


def logoutUser(request):
  logout(request)
  messages.info(request, 'user was logged out')
  return redirect('login')


def registerUser(request):
  page = 'register'
  form = CustomUserCreationForm()
  if request.method == 'POST':
    form = CustomUserCreationForm(request.POST)
    if form.is_valid():
      user = form.save(commit=False)
      user.username = user.username.lower()
      user.save()
      messages.success(request, 'User account was created!')
      return redirect('login')
    else:
      messages.error(request, 'An error occurred during registeration')
  context = {'page': page, 'form': form}
  return render(request, 'signupin.html', context)

templates/cancel.html
{% extends 'main.html' %} {% load static %} {% block content %}
<!-- -->
<section class="success">
  <div class="success-container">
    <div class="success-head">
      <div>
        <h3>Current Plan Details</h3>
        <span style="color: red; background-color: rgba(255, 0, 0, 0.2)"
          >Cancelled</span
        >
      </div>
    </div>
    <p class="plan-name">{{plan_name}}</p>
    <p class="plan-price">
      {{price}}/{% if month_year %} Month {% else %} Year {% endif %}
    </p>
    <a class="choose-plan" href="{% url 'payment' %}">Choose Plan</a>
    <p class="sub-notice">
      Your Subscription has been cancelled. And you will looose access on {{e}}.
    </p>
  </div>
</section>
{% endblock content %}

templates/header.html
<nav>
  <div class="nav-div">
    <a class="hover-anchor" href="{% url 'home' %}"><h4>Home</h4></a>
    <a class="hover-anchor" href="{% url 'pricing' %}"><h4>pricing</h4></a>

    {% if user.is_authenticated %}
    <a class="hover-anchor" href="{% url 'logout' %}"><h4>Logout</h4></a>
    {% else %}
    <a class="hover-anchor" href="{% url 'login' %}"><h4>Login</h4></a>
    {% endif %}
  </div>
</nav>

templates/index.html
{% extends 'main.html' %} {% load static %} {% block content %}
<!--revealAnimation-->

<section class="index">
  <div class="heading">
    <h1>Richpanel</h1>
    <h1>Assignment</h1>
  </div>

</section>

{% endblock content %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Main</title>

    <!-- swup.js -->
    <script src="https://unpkg.com/swup@3"></script>
    <script src="https://unpkg.com/@swup/forms-plugin@2"></script>
    <script src="https://unpkg.com/@swup/js-plugin@2"></script>
    <script src="https://unpkg.com/@swup/preload-plugin@2"></script>
    <script src="https://unpkg.com/@swup/debug-plugin@3"></script>

    <!-- stripe -->
    <script src="https://js.stripe.com/v3/"></script>
    <!-- favicon -->
    <link rel="icon" href="{% static 'public/favicon.ico' %}" />

    <!-- lenis -->
    <script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js"></script>
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="../static/css/styles.css" />
  </head>

  <body>
    <main>
      {% include 'header.html' %}
      <!--content of a web page-->
      {% if messages %} {% for message in messages %}
      <div class="alert alert--{{ message.tags }}">
        <p class="alert_message">{{ message }}</p>
      </div>
      {% endfor %} {% endif %} {%block content %}
      <!--  -->
      {% endblock content %}

      <!--footer-->
    </main>
    {% include 'footer.html' %}
  </body>
</html>

templates/payment.html
{% extends 'main.html' %} {% load static %} {% block content %}
<!-- -->

<script src="https://js.stripe.com/v3/"></script>
<!--  -->
<section class="payment">
  <div class="container">
    <div class="left-container">
      <h3>Complete your payment</h3>
      <p>enter your credit or debit card details below</p>
      <form id="payment-form" method="POST" data-secret="{{ client_secret }}">
        {% csrf_token %}
        <div id="card-element">
          <!-- Elements will create input elements here -->
        </div>

        <!-- We'll put the error messages in this element -->
        <div id="card-errors" role="alert"></div>

        <button class="action-btn" id="card-button">Submit Payment</button>
      </form>
    </div>
    <div class="right-container">
      <h3>order summary</h3>
      <div class="plan-name">
        <p>Plan Name</p>
        <span>{{plan_name}}</span>
      </div>
      <div class="billing-cycle">
        <p>Billing Cycle</p>
        <span>{% if month_year %} Month {% else %} Year {% endif %}</span>
      </div>
      <div class="plan-price">
        <p>Plan Price</p>
        <span> ₹{{price}}</span>
      </div>
    </div>
  </div>
</section>
<script>
  var stripe = Stripe(
    "pk_test_51NdFIbSIW5Rzk48Y3uGTVznYgjqTOJ1cU96lAk5pdBUKyzRElIWUymkI5slb1PcMRWdI8nNEo2PIqY3a42qFlrhp00Etgf5vzM"
  );

  var elements = stripe.elements();
  var elements = stripe.elements();
  var style = {
    base: {
      color: "#32325d",
    },
  };

  var card = elements.create("card", { style: style });
  card.on("change", ({ error }) => {
    let displayError = document.getElementById("card-errors");
    if (error) {
      displayError.textContent = error.message;
    } else {
      displayError.textContent = "";
    }
  });
  card.mount("#card-element");

  var form = document.getElementById("payment-form");
  var clientSecret = form.dataset.secret;

  form.addEventListener("submit", function (ev) {
    ev.preventDefault();
    // If the client secret was rendered server-side as a data-secret attribute
    // on the <form> element, you can retrieve it here by calling `form.dataset.secret`
    stripe
      .confirmCardPayment(clientSecret, {
        payment_method: {
          card: card,
          billing_details: {
            name: "{{profile}}",
          },
        },
      })
      .then(function (result) {
        if (result.error) {
          // Show error to your customer (for example, insufficient funds)
          console.log(result.error.message);
        } else {
          // The payment has been processed!
          if (result.paymentIntent.status === "succeeded") {
            // Show a success message to your customer
            // There's a risk of the customer closing the window before callback
            // execution. Set up a webhook or plugin to listen for the
            // payment_intent.succeeded event that handles any business critical
            // post-payment actions.
          }
        }
      });
    form.submit();
  });
</script>
{% endblock content %}

templates/pricing.html
{% extends 'main.html' %} {% load static %} {% block content %}
<!-- -->
<section class="pricing">
  <form class="pricing-form" method="post">
    {% csrf_token %}
    <div class="form--field toggle-switch">
      <div class="form--field-embed">
        <input
          class="mon_yr-check"
          type="checkbox"
          name="month_year"
          id="id_month_year"
          checked=""
        />
        Monthly (Tick) / Yearly (Untick)
      </div>
    </div>

    <div class="form--field pricing-plan">
      <div class="form--field-embed">
        <div id="id_plan_name">
          <div>
            <label for="id_plan_name_0"
              ><input
                type="radio"
                name="plan_name"
                value="mobile"
                required=""
                id="id_plan_name_0"
              />
            </label>
            Mobile
          </div>
          <div>
            <label for="id_plan_name_1"
              ><input
                type="radio"
                name="plan_name"
                value="basic"
                required=""
                id="id_plan_name_1"
                checked=""
              />
            </label>
            Basic
          </div>
          <div>
            <label for="id_plan_name_2"
              ><input
                type="radio"
                name="plan_name"
                value="standard"
                required=""
                id="id_plan_name_2"
              />
            </label>
            Standard
          </div>
          <div>
            <label for="id_plan_name_3"
              ><input
                type="radio"
                name="plan_name"
                value="premium"
                required=""
                id="id_plan_name_3"
              />
            </label>
            Premium
          </div>
        </div>
      </div>
    </div>

    <button class="next-btn action-btn" type="submit">Submit</button>
  </form>
</section>
{% endblock content %}

templates/signupin.html
{% extends 'main.html' %}
<!--  -->
{% block title %} {{ page }} {% endblock %}
<!--  -->
{% block content %}

<section class="signupin">
  <div class="signupin-container">
    <!-- Sign Up Form -->

    <div class="forms">
      {% if page == 'register' %}
      <h3>Create account</h3>
      <form method="POST" class="form" autocomplete="off" data-swup-form>
        {% csrf_token %}
        <!--  -->
        {% for field in form %}
        <div class="form--field">
          <div class="form--field-embed">
            <label class="form--label">{{field.label}}</label>
            {{field}}
          </div>
        </div>
        {% for error in field.errors %}
        <span style="color: red" class="field--errors">{{error}}</span>
        {% endfor %} {% endfor %}

        <button class="action-btn" type="submit">Register</button>
        <div class="form--switch">
          Already have an account? <a href="{% url 'login' %}">Sign In</a>
        </div>
      </form>

      {% else %}
      <!-- Sign In Form -->
      <h3>Login to your account</h3>
      <form
        method="POST"
        class="form"
        id="login"
        autocompletete="off"
        data-swup-form
      >
        {% csrf_token %} {% for field in form %}
        <div class="form--field">
          <div class="form--field-embed">
            <label class="form--label">{{field.label}}</label>
            {{field}}
          </div>
        </div>
        {% for error in field.errors %}
        <span style="color: red" class="field--errors">{{error}}</span>
        {% endfor %} {% endfor %}
        <!--  -->
        <div class="checkbox-rem">
          <input
            class="checkbox-remember"
            type="checkbox"
            name="Remember me"
            id=""
          />Remember Me
        </div>

        <button class="action-btn" type="submit">Login</button>
        <div class="form--switch">
          Don't have an account? <a href="{% url 'register' %}">Sign Up</a>
        </div>
      </form>

      {% endif %}
    </div>
  </div>
</section>

{% endblock content %}

templates/success.html
{% extends 'main.html' %} {% load static %} {% block content %}
<!-- -->
<section class="success">
  <div class="success-container">
    <div class="success-head">
      <div>
        <h3>Current Plan Details</h3>
        <span>Active</span>
      </div>
      <form method="POST">
        {% csrf_token %}
        <button class="cancel-btn" id="card-button">Cancel</button>
      </form>
    </div>
    <p class="plan-name">{{plan_name}}</p>
    <p class="plan-price">
      {{price}}/{% if month_year %} Month {% else %} Year {% endif %}
    </p>
    <a class="choose-plan" href="{% url 'payment' %}">Choose Plan</a>
    <p class="sub-notice">
      Your Subscription has started on {{s}}. and will renew on {{e}}.
    </p>
  </div>
</section>
{% endblock content %}